# Generated by Django 6.0.3 on 2026-09-02 17:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_id",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        unique=True,
                        verbose_name="შეკვეთის ID (Flitt Order ID)",
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("monthly", "ყოველთვიური გამოწერა (50 ₾ / თვე)"),
                            ("yearly", "1-წლიანი სრული პაკეტი (400 ₾ / წელი)"),
                        ],
                        max_length=20,
                        verbose_name="პაკეტის ტიპი",
                    ),
                ),
                (
                    "amount_gel",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="თანხა (₾ GEL)"
                    ),
                ),
                (
                    "amount_tetri",
                    models.PositiveIntegerField(verbose_name="თანხა თეთრებში (Tetri)"),
                ),
                (
                    "currency",
                    models.CharField(
                        default="GEL", max_length=3, verbose_name="ვალუტა"
                    ),
                ),
                (
                    "order_desc",
                    models.CharField(max_length=255, verbose_name="შეკვეთის აღწერა"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "შექმნილია (Created)"),
                            ("processing", "მუშავდება (Processing)"),
                            ("approved", "დამტკიცებულია / გადახდილია (Approved)"),
                            ("declined", "უარყოფილია (Declined)"),
                            ("expired", "ვადაგასულია (Expired)"),
                            ("reversed", "გაუქმებულია / დაბრუნებულია (Reversed)"),
                        ],
                        default="created",
                        max_length=30,
                        verbose_name="სტატუსი",
                    ),
                ),
                (
                    "is_subscription",
                    models.BooleanField(
                        default=False, verbose_name="გამოწერაა (Subscription)"
                    ),
                ),
                (
                    "flitt_payment_id",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Flitt Payment ID",
                    ),
                ),
                (
                    "masked_card",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=32,
                        verbose_name="დაფარული ბარათი",
                    ),
                ),
                (
                    "card_type",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=32,
                        verbose_name="ბარათის ტიპი",
                    ),
                ),
                (
                    "checkout_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Flitt Checkout URL",
                    ),
                ),
                (
                    "response_status",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=32,
                        verbose_name="Flitt Response Status",
                    ),
                ),
                (
                    "response_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=32,
                        verbose_name="Flitt Response Code",
                    ),
                ),
                (
                    "response_description",
                    models.TextField(
                        blank=True, default="", verbose_name="Flitt აღწერა"
                    ),
                ),
                (
                    "raw_response",
                    models.JSONField(
                        blank=True,
                        null=True,
                        verbose_name="სრული Callback / Response JSON",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="შექმნის თარიღი"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="განახლების თარიღი"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="მომხმარებელი",
                    ),
                ),
            ],
            options={
                "verbose_name": "გადახდის შეკვეთა",
                "verbose_name_plural": "გადახდის შეკვეთები",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserSubscriptionAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("monthly", "ყოველთვიური გამოწერა (50 ₾ / თვე)"),
                            ("yearly", "1-წლიანი სრული პაკეტი (400 ₾ / წელი)"),
                        ],
                        max_length=20,
                        verbose_name="აქტიური პაკეტის ტიპი",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="აქტიურია"),
                ),
                (
                    "auto_renew",
                    models.BooleanField(
                        default=True, verbose_name="ავტომატური განახლება"
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="დაწყების თარიღი",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(verbose_name="ვადის გასვლის თარიღი"),
                ),
                (
                    "rectoken",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Flitt Recurring Token",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="შექმნის თარიღი"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="განახლების თარიღი"
                    ),
                ),
                (
                    "last_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="payments.paymentorder",
                        verbose_name="ბოლო გადახდის შეკვეთა",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_access",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="მომხმარებელი",
                    ),
                ),
            ],
            options={
                "verbose_name": "მომხმარებლის წვდომა / გამოწერა",
                "verbose_name_plural": "მომხმარებლების წვდომები / გამოწერები",
            },
        ),
    ]
