# Generated by Django 6.0.3 on 2026-09-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentorder",
            name="payment_token",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Flitt Payment Token",
            ),
        ),
    ]
