# Generated by Django 6.0.3 on 2026-09-02 20:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_alter_chapter_options_alter_course_options_and_more"),
        ("payments", "0002_paymentorder_payment_token"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentorder",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_orders",
                to="courses.course",
                verbose_name="არჩეული კურსი",
            ),
        ),
        migrations.CreateModel(
            name="UserCourseAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("monthly", "ყოველთვიური გამოწერა (50 ₾ / თვე)"),
                            ("yearly", "1-წლიანი სრული პაკეტი (400 ₾ / წელი)"),
                        ],
                        max_length=20,
                        verbose_name="აქტიური პაკეტის ტიპი",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="აქტიურია"),
                ),
                (
                    "auto_renew",
                    models.BooleanField(
                        default=True, verbose_name="ავტომატური განახლება"
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="დაწყების თარიღი",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(verbose_name="ვადის გასვლის თარიღი"),
                ),
                (
                    "rectoken",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Flitt Recurring Token",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="შექმნის თარიღი"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="განახლების თარიღი"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_accesses",
                        to="courses.course",
                        verbose_name="კურსი",
                    ),
                ),
                (
                    "last_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="payments.paymentorder",
                        verbose_name="ბოლო გადახდის შეკვეთა",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_accesses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="მომხმარებელი",
                    ),
                ),
            ],
            options={
                "verbose_name": "კურსის წვდომა",
                "verbose_name_plural": "კურსების წვდომები",
                "unique_together": {("user", "course")},
            },
        ),
    ]
