# Generated by Django 6.0.3 on 2026-09-02 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_paymentorder_course_usercourseaccess"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserSubscriptionAccess",
        ),
    ]
