# Generated by Django 6.0.3 on 2026-09-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="book_author",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="წიგნის ავტორი"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="grade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("IV", "IV"),
                    ("V", "V"),
                    ("VI", "VI"),
                    ("VII", "VII"),
                    ("VIII", "VIII"),
                    ("IX", "IX"),
                ],
                default="",
                max_length=10,
                verbose_name="კლასი",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="parent_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=150,
                verbose_name="მშობლის სახელი და გვარი",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="student_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=150,
                verbose_name="მოსწავლის სახელი და გვარი",
            ),
        ),
    ]
