# Generated by Django 6.0.3 on 2026-09-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="book_author",
            field=models.CharField(
                blank=True,
                default="",
                max_length=150,
                verbose_name="სახელმძღვანელოს ავტორი",
            ),
        ),
    ]
