# Generated by Django 6.0.3 on 2026-05-31 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="course",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
