# Generated by Django 6.0.3 on 2026-06-01 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_course_options_course_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(
                blank=True,
                default="https://www.youtube.com/embed/PA-f0MjuK_Q",
                null=True,
            ),
        ),
    ]
