# Generated by Django 6.0.3 on 2026-09-02 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_lesson_video_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chapter",
            options={
                "ordering": ["order"],
                "verbose_name": "თავი (Chapter)",
                "verbose_name_plural": "თავები (Chapters)",
            },
        ),
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["order"],
                "verbose_name": "კურსი",
                "verbose_name_plural": "კურსები",
            },
        ),
        migrations.AlterModelOptions(
            name="learningobjective",
            options={
                "verbose_name": "სასწავლო მიზანი",
                "verbose_name_plural": "სასწავლო მიზნები",
            },
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ["order"],
                "verbose_name": "გაკვეთილი (Lesson)",
                "verbose_name_plural": "გაკვეთილები (Lessons)",
            },
        ),
        migrations.AlterField(
            model_name="chapter",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapters",
                to="courses.course",
                verbose_name="კურსი",
            ),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="თანმიმდევრობა"),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="title",
            field=models.CharField(
                max_length=150, verbose_name="თავის სახელი (Chapter Title)"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="duration",
            field=models.CharField(max_length=50, verbose_name="ხანგრძლივობა"),
        ),
        migrations.AlterField(
            model_name="course",
            name="grade",
            field=models.CharField(max_length=50, verbose_name="კლასი"),
        ),
        migrations.AlterField(
            model_name="course",
            name="instructor_name",
            field=models.CharField(max_length=150, verbose_name="მასწავლებელი"),
        ),
        migrations.AlterField(
            model_name="course",
            name="lessons_count",
            field=models.IntegerField(default=0, verbose_name="გაკვეთილების რაოდენობა"),
        ),
        migrations.AlterField(
            model_name="course",
            name="long_description",
            field=models.TextField(verbose_name="სრული აღწერა"),
        ),
        migrations.AlterField(
            model_name="course",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="თანმიმდევრობა"),
        ),
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="ფასი"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="short_description",
            field=models.TextField(verbose_name="მოკლე აღწერა"),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(max_length=200, verbose_name="სათაური"),
        ),
        migrations.AlterField(
            model_name="course",
            name="video_url",
            field=models.URLField(verbose_name="შესავალი ვიდეოს ბმული"),
        ),
        migrations.AlterField(
            model_name="learningobjective",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="objectives",
                to="courses.course",
                verbose_name="კურსი",
            ),
        ),
        migrations.AlterField(
            model_name="learningobjective",
            name="text",
            field=models.CharField(
                max_length=255, verbose_name="მიზანი / რას ისწავლით"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="chapter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="courses.chapter",
                verbose_name="თავი",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="duration",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="ხანგრძლივობა"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="icon",
            field=models.CharField(
                blank=True,
                default="bx-play-circle",
                max_length=50,
                verbose_name="აიკონი",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="თანმიმდევრობა"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="title",
            field=models.CharField(max_length=200, verbose_name="გაკვეთილის სახელი"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(
                blank=True,
                default="https://www.youtube.com/embed/PA-f0MjuK_Q",
                null=True,
                verbose_name="ვიდეოს ბმული (Video URL)",
            ),
        ),
    ]
